apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: smstore-partner-site
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - *.tiemcuatui.com
    secretName: wildcard-tiemcuatui-com-tls
  rules:
  - host: *.tiemcuatui.com
    http:
      paths:
      - backend:
          serviceName: smstore-partner-site
          servicePort: 80
