query fetchProducts(
  $where: products_bool_exp
  $offset: Int
  $limit: Int
) {
  products(
    offset: $offset
    limit: $limit
    where: $where,
    order_by: { order_no: desc }
  ) {
    id
    name
    slug
    is_active
    in_stock
    price
    order_no
    category {
      id
      name
      slug
    }
    images(
      offset: 0,
      limit: 1,
      order_by: { id: asc }
    ) {
      id
      path
    }
  }
}