query fetchCategories(
  $store_id: Int
) {
  categories(
    where: {
      store_id: { _eq: $store_id }
      parent_id: {_is_null: true},
      is_active: {_eq: true}
    },
    order_by: { order_no: desc }
  ) {
    id
    parent_id
    name
    slug
    
    children(
      where: { is_active: {_eq: true} },
      order_by: { order_no: desc }
    ) {
      id
      parent_id
      name
      slug
      
      children(
        where: { is_active: {_eq: true} },
        order_by: { order_no: desc }
      ) {
        id
        parent_id
        name
        slug
        
        
      }
    }
  }
}